SymCryptEngine/src/sc_ossl.c, SymCryptEngine/src/sc_ossl_ecc.c, SymCryptEngine/src/sc_ossl_ecc.h, SymCryptEngine/src/sc_ossl_rsa.c
+ In sc_ossl_rsa_finish free exdata if it is non-NULL
+ And do not dereference exdata if it is NULL
+ In ECC, do not initialize exdata until we know we will definitely be
using it (and not falling back to default implementation)
+ Rather than using the curve to determine whether to free exdata
members, use the initialized field
+ Always free the exdata if it is non-NULL
+ Also in ECDSA, handle DER encoded ECDSA signatures for P192 and P224
=> Fixes for some memory leaks

SymCryptEngine/src/sc_ossl_digests.c, SymCryptEngine/src/sc_ossl_ecc.c, SymCryptEngine/src/sc_ossl_rsa.c, SymCryptEngine/src/sc_ossl_rsapss.c
+ Hopefully handing allocation/freeing of SymCrypt digest state entirely
to OpenSSL should avoid leaks in HMAC which Ming-Wei observes but I
have not been able to reproduce
+ Reduces complexity and lines of code anyway, so seems like a step in
the right direction
+ Free allocated public key on successful ECDH
+ Error in the engine when flen provided to RSA is too big, rather than
changing the value to read a prefix of the provided buffer
+ Also explicitly write to the amount of memory that is specified in
the RSA documentation:
https://www.openssl.org/docs/man1.1.1/man3/RSA_private_decrypt.html
=> Simplify digest memory allocation

SymCryptEngine/dynamic/CMakeLists.txt
Failed to load the libsymcryptengine caused by the crypto not loaded in python3. The ssl module will not call into the symcrypt without any display error.
The error message is  "undefined symbol: RSA_meth_get_pub_dec" during the debug.
The debug as below, the lib crypto is not loaded:
ENGINE_ctrl_cmd_string (e=0x55f821dc7370, cmd_name=0x7fdd7f6ae128 "LOAD", arg=0x0, cmd_optional=0) at ../crypto/engine/eng_ctrl.c:231
231     ../crypto/engine/eng_ctrl.c: No such file or directory.
(gdb) p *e
$1 = {id = 0x7fdd7f6ae1b0 "dynamic", name = 0x7fdd7f6ae1b8 "Dynamic engine loading support", rsa_meth = 0x0, dsa_meth = 0x0, dh_meth = 0x0, ec_meth = 0x0, rand_meth = 0x0, ciphers = 0x0, digests = 0x0, pkey_meths = 0x0, pkey_asn1_meths = 0x0, 
destroy = 0x0, init = 0x7fdd7f589201 <dynamic_init>, finish …
=> [build]: Fix the loading symcryengine issue

SymCryptEngine/src/sc_ossl_helpers.h
+ Fixes build break (#15) when trying to build SymCrypt-OpenSSL against older
SymCrypt headers in a non-Windows environment
=> Define _Return_type_success_ to nothing if it is not already defined

CMakeLists.txt, README.md, SslPlay/CMakeLists.txt, SymCryptEngine/dynamic/CMakeLists.txt, SymCryptEngine/src/sc_ossl_helpers.c, SymCryptEngine/src/sc_ossl_helpers.h, SymCryptEngine/static/CMakeLists.txt, cmake-toolchain/LinuxUserMode-AMD64.cmake, cmake-toolchain/LinuxUserMode-ARM64.cmake
+ Update README on how to use them
+ Compile out debug and info logging when building a release version of
the engine, only leaving error logging
=> Introduce cmake-toolchain files for Linux AMD64 and ARM64

SymCryptEngine/src/sc_ossl_ciphers.c
+ CCM support with the EVP APIs is a bit strange, we track the stage of
the process of performing CCM encryption with SCOSSL_CCM_STAGE and
document how callers can move a context from one state to the next
+ Make some tweaks to GCM in preparation for supporting variable IV
length in the future and to use EVP constants rather than locally
defined versions to improve clarity a bit
=> Add AES-CCM support to Engine

SymCryptEngine/src/sc_ossl.c
Now that this is defined in SymCrypt, can remove this.
=> Remove placeholder rng

SslPlay/SslPlay.cpp, SymCryptEngine/dynamic/CMakeLists.txt, SymCryptEngine/src/sc_ossl.c, SymCryptEngine/src/sc_ossl_ciphers.c, SymCryptEngine/src/sc_ossl_ciphers.h, SymCryptEngine/src/sc_ossl_dh.c, SymCryptEngine/src/sc_ossl_dh.h, SymCryptEngine/src/sc_ossl_digests.c, SymCryptEngine/src/sc_ossl_digests.h, SymCryptEngine/src/sc_ossl_ecc.c, SymCryptEngine/src/sc_ossl_ecc.h, SymCryptEngine/src/sc_ossl_helpers.c, SymCryptEngine/src/sc_ossl_helpers.h, SymCryptEngine/src/sc_ossl_hkdf.c, SymCryptEngine/src/sc_ossl_pkey_meths.c, SymCryptEngine/src/sc_ossl_pkey_meths.h, SymCryptEngine/src/sc_ossl_rand.c, SymCryptEngine/src/sc_ossl_rand.h, SymCryptEngine/src/sc_ossl_rsa.c, SymCryptEngine/src/sc_ossl_rsa.h, SymCryptEngine/src/sc_ossl_rsapss.c, SymCryptEngine/src/sc_ossl_tls1prf.c, SymCryptEngine/src/sc_ossl_tls1prf.h, SymCryptEngine/static/CMakeLists.txt
+ Enable compiler warnings for C source files
+ Fix various compiler warnings (unsigned/signed comparison, unused
variables, etc.)
+ Remove redundant information from SCOSSL data structures
+ Remove redundant includes
+ Initialize long-lived static variables once at Engine load time,
rather than on demand to avoid race conditions when algorithms are
called concurrently without needing to introduce locking.
+ Check various returns for OpenSSL functions (e.g. BN_bin2bn et. al)
and gracefully error rather than potentially failing in unexpected
ways in low memory conditions
+ Fix memory leaks in new FFC DH implementation
+ Ensure all externally visible symbols have a scossl or sc_ossl prefix
(should settle on a single prefix in a followup PR)
+ Fallback to OpenSSL for ECDSA signatures with a …
=> Address various issues found in Code Review

CMakeLists.txt, SymCryptEngine/dynamic/CMakeLists.txt, cmake-toolchain/LinuxUserMode-ARM64.cmake
- Only set cross-compilation options when cross-compiling
- Install engine to OpenSSL ENGINESDIR
=> CMake compilation fixes for embedded platforms

SslPlay/SslPlay.cpp, SymCryptEngine/src/scossl_pkey_meths.c
+ Previously would only fallback for RSA keys, not specifically RSA-PSS
keys
+ Add test cases for DigestSign/Verify with RSA-PSS
=> When verifying RSA-PSS signature with auto-saltlen always fallback

SslPlay/SslPlay.cpp, SymCryptEngine/src/scossl.c, SymCryptEngine/src/scossl_ciphers.c, SymCryptEngine/src/scossl_dh.c, SymCryptEngine/src/scossl_digests.c, SymCryptEngine/src/scossl_ecc.c, SymCryptEngine/src/scossl_helpers.c, SymCryptEngine/src/scossl_helpers.h, SymCryptEngine/src/scossl_hkdf.c, SymCryptEngine/src/scossl_pkey_meths.c, SymCryptEngine/src/scossl_rsa.c, SymCryptEngine/src/scossl_rsapss.c, SymCryptEngine/src/scossl_tls1prf.c
+ This is in addition to logging to stderr or a log file specified by
the caller
+ For now do not specify all the functions which can generate errors and
error reasons up front, but instead log all SCOSSL errors as being for
an unknown function and with a generic reason of "Error".
+ Log additional information with the errors indicating the function
and error reason using the existing data that SCOSSL provides to
error logging functions
=> Log SCOSSL errors to OpenSSL's ERR infrastructure

CMakeLists.txt, README.md, SslPlay/CMakeLists.txt, SslPlay/SslPlay.cpp, SymCryptEngine/dynamic/CMakeLists.txt, SymCryptEngine/dynamic/OpenSSLConfig.conf, SymCryptEngine/inc/scossl.h, SymCryptEngine/src/scossl.c, SymCryptEngine/src/scossl_helpers.c, SymCryptEngine/src/scossl_helpers.h
+ Do not leak CRYPTO_RWLOCK
+ Introduce ability to set different levels of logging verbosity for
using OpenSSL ERR and stderr/logfile. Set default level of logging for
OpenSSL ERR to ERROR to avoid problems in OpenSSL unit tests.
+ Update Engine id and name
=> Various logging tweaks

SymCryptEngine/dynamic/CMakeLists.txt, SymCryptEngine/src/scossl.c, SymCryptEngine/src/scossl_helpers.c
This PR includes a few changes to prepare for some upcoming SymCrypt changes. It should be backwards-compatible with existing versions of SymCrypt.
- Use `SYMCRYPT_MODULE_INIT()` macro instead of explicitly calling `SymCryptModuleInit`. The macro automatically passes in the right arguments, and will work with the new version which is removing the patch version as an argument.
- Remove reference to `SYMCRYPT_UNUSED` error code, which is being removed,
- Use CMake's [find_library](https://cmake.org/cmake/help/latest/command/find_library.html) function to find the symcrypt library on the system. This will hopefully be slightly more robust than just directly specifying the library name in `target_link_libraries`. In the future, we may want to create a CMake package config for SymCrypt and use …
=> Prepare for upcoming SymCrypt API changes

SymCryptEngine/static/CMakeLists.txt
+ Enables simple use of cmake install in Mariner build
=> Do not Install static SCOSSL library by default

SymCryptEngine/src/scossl_hkdf.c, SymCryptEngine/src/scossl_hkdf.h, SymCryptEngine/src/scossl_tls1prf.c, SymCryptEngine/src/scossl_tls1prf.h
+ Use proposed new SymCrypt API in order to produce PRK in Extract-only operation
+ Use existing SymCrypt APIs to consume a PRK in Expand-only operation
+ Change \_In\_ annotation to \_Inout\_ for keylen parameter in EVP_KDF derive functions
=> Complete HKDF implementation to use SymCrypt implementation for partial HKDF operations

CMakeLists.txt, README.md, SslPlay/SslPlay.cpp, SymCryptEngine/dynamic/CMakeLists.txt, SymCryptEngine/src/scossl_ecc.c, SymCryptEngine/src/scossl_rsa.c, SymCryptEngine/src/scossl_rsapss.c
+ Allow libsymcrypt to be found from root of SymCrypt-OpenSSL directory
+ Update README to make compilation instructions a little clearer
+ Add CMake project version/description
=> Various tidying to reduce warnings in build

SymCryptEngine/src/scossl_ciphers.c
+ This is required for EVP_CIPHER_CTX reuse with different IVs, should
fix bug observed in OpenSSH
=> Set AES-GCM operationInProgress to 0 when IV is explicitly set

SymCryptEngine/src/scossl.c, SymCryptEngine/src/scossl_ciphers.c, SymCryptEngine/src/scossl_dh.c, SymCryptEngine/src/scossl_ecc.c, SymCryptEngine/src/scossl_pkey_meths.c, SymCryptEngine/src/scossl_rsa.c, SymCryptEngine/src/scossl_rsapss.c
+ Use new SymCrypt flags to specify asymmetric key purposes
+ Avoid crash on invalid RSA-PSS input
+ Avoid double free if Engine is destroyed multiple times
+ Tweak AES-GCM to only Finalize when passed `in` pointer of NULL
=> Avoid redundant ECC tests on key generation

CMakeLists.txt
In some environments, we use CMake's RelWithDebInfo build type so that we can do an optimized build but still get debug symbols, which we then copy and strip from the binary in a separate step. When building this way, we don't want the `DBG` flag to be set.
=> Do not set -DDBG=1 when build type is RelWithDebInfo

SymCryptEngine/src/scossl_ciphers.c
+ This means libssl will have to call AES-CBC and HMAC separately, which
is easier for us to route to SymCrypt
=> Intercept stitched AES-CBC + HMAC ciphers and disable them

SymCryptEngine/src/scossl.c
+ On SCOSSL bind, load all EVP ciphers and then remove the stitched ciphers that we do not support in SCOSSL. This is a workaround for callers using EVP_get_cipherbyname.
=> Explicitly remove stitched EVP ciphers from OpenSSL internal list

SymCryptEngine/src/scossl_ciphers.c
Reverts microsoft/SymCrypt-OpenSSL#50
Further testing shows that this change did not intercept libssl's use of stitched
AES-CBC + HMAC ciphers as expected - and in certain circumstances it can cause
internal errors. 
#54 is the only required change.
=> Revert "Intercept stitched AES-CBC + HMAC ciphers and disable them"

SymCryptProvider/CMakeLists.txt, SymCryptProvider/src/p_scossl_base.c
The SymCrypt provider receives a dispatch table for upcalls in its init function. The provider should use these functions to avoid a circular dependency on libcrypto.
=> Use dispatch table passed to provider

ScosslCommon/inc/scossl_helpers.h, SymCryptEngine/src/e_scossl_ciphers.c, SymCryptEngine/src/e_scossl_digests.c, SymCryptEngine/src/e_scossl_hmac.c, SymCryptProvider/src/ciphers/p_scossl_aes.c, SymCryptProvider/src/ciphers/p_scossl_aes_aead.c, SymCryptProvider/src/ciphers/p_scossl_aes_xts.c, SymCryptProvider/src/p_scossl_base.c, SymCryptProvider/src/p_scossl_digests.c
+ Previously SCOSSL would rely on allocations made by libcrypto being at least 16-byte aligned for 64-bit platforms. This was normally true, but in some environments where the allocator is modified, only 8-byte alignment was being provided.
+ Should address #59
=> Ensure that SymCrypt structures have sufficient alignment

ScosslCommon/inc/scossl_rsa.h, ScosslCommon/src/scossl_rsa.c, SymCryptProvider/CMakeLists.txt, SymCryptProvider/src/asymcipher/p_scossl_rsa_cipher.c, SymCryptProvider/src/ciphers/p_scossl_aes_xts.c, SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c, SymCryptProvider/src/p_scossl_base.c, SymCryptProvider/src/signature/p_scossl_rsa_signature.c
Adds support for AES-XTS and RSA-PSS verification with auto salt-len detection using new SymCrypt API surface.
=> Add support for AES-XTS and RSA-PSS with auto salt-len

ScosslCommon/CMakeLists.txt, ScosslCommon/inc/scossl_dh.h, ScosslCommon/inc/scossl_helpers.h, ScosslCommon/src/scossl_dh.c, ScosslCommon/src/scossl_helpers.c, SymCryptEngine/src/e_scossl_dh.c, SymCryptProvider/CMakeLists.txt, SymCryptProvider/src/keyexch/p_scossl_dh.c, SymCryptProvider/src/keyexch/p_scossl_dh.h, SymCryptProvider/src/keymgmt/p_scossl_dh_keymgmt.c, SymCryptProvider/src/p_scossl_base.c
- Add Diffie-Hellman key exchange to the provider
- Added DH key management interface
- Supports import by group parameters for app compat, but a warning is logged
- Added DH key exchange interface
- Supports X9.42 for app compat. This follows the default provider model of creating a new EVP_KDF and feeding it the result of the derivation. Import of X9.42 formatted keys is offloaded to the default provider
- Refactored common code from engine to share with provider
- Derive function remains separate due to differences in the requirements between the provider and engine
- Added support for added NID_modp_* in OpenSSL 3
- Added support for import by group parameters due to requirement in the provider
=> Provider DH

SymCryptProvider/inc/p_scossl_base.h.in, SymCryptProvider/src/p_scossl_base.c, SymCryptProvider/src/signature/p_scossl_rsa_signature.c
RSA_PSS_SALTLEN_AUTO_DIGEST_MAX and EVP_MD_CTX_dup weren't added until OpenSSL 3.1. This PR fixes builds for 3.0 by:
- Wrapping RSA_PSS_SALTLEN_AUTO_DIGEST_MAX with #ifdef (same thing as in ScosslCommon)
- Define EVP_MD_CTX_dup using the official 3.1 implementation if building on 3.0
=> Fix 3.0 compatability issues

ScosslCommon/inc/scossl_rsa.h, ScosslCommon/src/scossl_rsa.c, SymCryptEngine/src/e_scossl_rsa.c, SymCryptEngine/src/e_scossl_rsa.h, SymCryptEngine/src/e_scossl_rsapss.c, SymCryptProvider/src/asymcipher/p_scossl_rsa_cipher.c, SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c, SymCryptProvider/src/p_scossl_base.c, SymCryptProvider/src/p_scossl_rsa.c, SymCryptProvider/src/p_scossl_rsa.h, SymCryptProvider/src/signature/p_scossl_rsa_signature.c
The SymCrypt provider only supported PSS padded RSA if the key was imported through the RSA key management interface. RSASSA-PSS keys were not routed to the SymCrypt provider, and the keys' restrictions would not be properly handled. 
This PR addresses the gap by adding the RSASSA-PSS key management interface and updating the RSA signature interface to enforce the restrictions associated with RSASSA-PSS keys.
=> Properly support restricted PSS keys

SymCryptProvider/CMakeLists.txt, SymCryptProvider/src/kdf/p_scossl_kbkdf.c, SymCryptProvider/src/mac/p_scossl_kmac.c, SymCryptProvider/src/mac/p_scossl_kmac.h, SymCryptProvider/src/p_scossl_base.c
This PR adds the KBKDF (SP800-108) interface to the SymCrypt provider. The following are supported:
Counter mode:
- HMAC-SHA1
- HMAC-SHA256
- HMAC-SHA384
- HMAC-SHA512
- HMAC-SHA3-256
- HMAC-SHA3-384
- HMAC-SHA3-512
- CMAC-AES128
- CMAC-AES192
- CMAC-AES256
KMAC:
- KMAC128
- KMAC256
=> Provider KBKDF (SP800-108)

SymCryptEngine/dynamic/CMakeLists.txt
Avoids incorrectly parsing cmake file resulting in installing the shared libraries in: `/usr/CACHE;PATH;Path to OpenSSL engines;lib/engines-1.1/symcryptengine.so`
Thanks to Alejandro Hernandez Samaniego for making this change (I'm just copying it from an internal patch).
=> Fix CMake file to avoid installing libraries incorrect path

SymCryptProvider/src/ciphers/p_scossl_aes.c, SymCryptProvider/src/keymgmt/p_scossl_ecc_keymgmt.c, SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c, SymCryptProvider/src/p_scossl_base.c
- Declare variable outside of case statement for compiler compatibility.
- Properly export 64-bit RSA public exponents.
- Move `keysinuseLock` initialization in copy context functions.
- Initialize `keysinuseLock` for context created in keygen functions.
- Suppress errors from the config API when loading keysinuse. These errors can be safely ignored by callers, but can cause failures at the SSL layer if they're left on the error stack.
=> Various provider bugfixes

SymCryptProvider/src/ciphers/p_scossl_aes.c, SymCryptProvider/src/keymgmt/p_scossl_ecc_keymgmt.c
Testing with tpm2 and SymCrypt-OpenSSL on Azure Linux 3 uncovered a compatibility issue and a bug. This PR addresses both.
- Add EC key X and Y coordinates to gettable EC key parameters
- Add missing AES parameters. These are always 0 but may be requested by some callers
- Make AES-CFB compatible with OpenSSL's stream cipher calling pattern.
- AES-CFB is expected to encrypt the entirety of inl on each cipher update call. The cipher final call should do nothing.
=> Fixes for tpm2

CMakeLists.txt, ScosslCommon/src/scossl_ecc.c, SymCryptProvider/src/ciphers/p_scossl_aes.c, SymCryptProvider/src/ciphers/p_scossl_aes_xts.c, SymCryptProvider/src/keyexch/p_scossl_dh.c, SymCryptProvider/src/keyexch/p_scossl_ecdh.c
This PR addresses behavior fixes for compatibility issues found when calling OpenSSL with the SymCryp provider though different wrapper libraries. These are behavior differences to make the SymCrypt provider act more like the default provider.
- Allow larger/smaller output sizes for ECDH secret. If the output size is smaller than the output of `SymCryptEcDhSecretAgreement`, the secret is truncated.
- Allow larger output sizes for DH secret.
- When `inl` passed to AES cipher update is zero, `*outl` should always be set to zero.
- Always return a sufficiently large buffer size for ECDSA digest sign
=> Behavior fixes for API compatability

ScosslCommon/src/scossl_rsa.c, ScosslCommon/src/scossl_tls1prf.c
Some log messages were indicating that HMAC algorithms were not FIPS compliant, when really they were referring to the digest algorithm. This corrects the log messages.
=> Correct log messages to say hash where they said Hmac

README.md
In the README, it is mentioned that GCM IVs are restricted to 96 bits. It looks like that restriction was removed as part of https://github.com/microsoft/SymCrypt-OpenSSL/pull/80/.
=> Remove GCM nonce restriction comment

ScosslCommon/src/scossl_helpers.c, SymCryptEngine/src/e_scossl_rsa.c
- Fixes RSA decrypt fallback when padding is unsupported
- Turn default logging level to off to avoid printing unnecessary errors to stdout
=> Fix engine behavior

SymCryptProvider/CMakeLists.txt
usr/CACHE;PATH;Path to OpenSSL providers;lib/symcryptprovider.so
vs
usr/lib/ossl-modules/symcryptprovider.so
Signed-off-by: Alejandro Hernandez Samaniego <alhe@linux.microsoft.com>
=> cmake: fixup CMakeLists to avoid installing libraries in incorrect path

EvpTestRecipes/3.0/evpkdf_srtpkdf.txt, SymCryptProvider/CMakeLists.txt, SymCryptProvider/inc/scossl_provider.h, SymCryptProvider/src/kdf/p_scossl_srtpkdf.c, SymCryptProvider/src/p_scossl_base.c
This PR adds SRTP and SRTCP KDF to the SymCrypt provider. OpenSSL itself does not implement SRTP, but can be used as part of an implementation: https://docs.openssl.org/3.3/man3/SSL_CTX_set_tlsext_use_srtp.
- Add SRTP and SRTCP KDF
- Add custom parameters needed for using these KDFs with the SymCrypt provider to `symcrypt_provider.h`
- Add test cases
=> Add SRTP KDF

CMakeLists.txt, EvpTestRecipes/3.0/evpkdf_ss.txt, SymCryptProvider/CMakeLists.txt, SymCryptProvider/src/kdf/p_scossl_sskdf.c, SymCryptProvider/src/p_scossl_base.c
This PR adds SSKDF as specified in SP800-56C, and associated tests. This bumps the dependency on SymCrypt to 103.5.0, which introduces the KDF.
=> Add SSKDF (SP800-56C)

EvpTestRecipes/3.0/evppkey_kdf_hkdf.txt, EvpTestRecipes/3.0/evppkey_kdf_tls1_prf.txt, SymCryptProvider/CMakeLists.txt, SymCryptProvider/inc/p_scossl_base.h.in, SymCryptProvider/src/kdf/p_scossl_hkdf.c, SymCryptProvider/src/kdf/p_scossl_hkdf.h, SymCryptProvider/src/kdf/p_scossl_tls1prf.c, SymCryptProvider/src/kdf/p_scossl_tls1prf.h, SymCryptProvider/src/keyexch/p_scossl_kdf_keyexch.c, SymCryptProvider/src/keymgmt/p_scossl_kdf_keymgmt.c, SymCryptProvider/src/p_scossl_base.c, SymCryptProvider/src/p_scossl_rand.c
HKDF and TLS1-PRF were available in OpenSSL 1.1.1 through the EVP_PKEY API. OpenSSL 3 introduced the EVP_KDF API, but some callers may still be using the EVP_PKEY API for KDF and TLS1-PRF. We have previously relied on the default provider's key exchange wrapper for these KDFs, which exposes them to the EVP_PKEY API. If the default provider is not enabled, or the caller sets "fips=yes", then the KDFs are no longer available to EVP_PKEY. 
This PR adds a similar wrapper in the SymCrypt provider. Only TLS1-PRF and HKDF are needed for existing callers using EVP_PKEY functions. All other KDFs were not supported in OpenSSL 1.1.1, and new applications using those KDFs should use the EVP_KDF API.
=> HKDF and TLS1-PRF EVP_PKEY key exchange wrapper

SymCryptProvider/src/signature/p_scossl_rsa_signature.c
`md` is only set by `p_scossl_rsa_get_supported_md` when `EVP_MD_fetch` succeeds. This normally always succeeds, but if a digest is queried with no supporting provider, `md` is left unchanged. Some of the calling functions in the provider did not initialize `md` to NULL and tried to free `md` on failure leading to a crash.
=> Fix crash when using an unavailable digest in RSA sign/verify

ScosslCommon/src/scossl_aes_aead.c, ScosslCommon/src/scossl_ecc.c
This PR addresses some incorrect behavior in the provider. These fixes are for behavior that isn't strictly speaking correct, but likely won't cause real-world issues.
- Check that ECDSA signature is a sequence of two integers without trailing data
- Return authenticated bytes for AEAD ciphers if out is NULL
=> Provider behavior fixes

SymCryptProvider/src/digests/p_scossl_cshake.c, SymCryptProvider/src/digests/p_scossl_shake.c
SHAKE and CSHAKE allow the `OSSL_DIGEST_PARAM_XOFLEN` parameter to be set. This should only be used as the output length for the "final" function. The `outlen` parameter passed to the "squeeze" function should be used as the output length for that case.
This PR updates the SymCrypt provider's SHAKE and CSHAKE interface to use the correct output length for squeeze.
=> Fix SHAKE and CSHAKE squeeze output length

CMakeLists.txt, SymCryptProvider/inc/p_scossl_base.h.in, SymCryptProvider/src/p_scossl_base.c
The SymCrypt provider currently initialized SymCrypt with `SYMCRYPT_MODULE_INIT`. This macro expands to `SymCryptModuleInit` using the SymCrypt major and minor version defined in the SymCrypt headers. This makes the SymCrypt provider's minimum SymCrypt version the version it was compiled with, and not the minimum version it's ABI compatible with.
This PR adds CMAKE variables for the minimum SymCrypt version the project depends on. The SymCrypt provider uses these values in initialization, so the SymCrypt provider can be used with the lowest version of SymCrypt it's compatible with, regardless of which version it's compiled with.
=> Hardcode SymCrypt minimum version instead of using value in headers

EvpTestRecipes/3.0/evppkey_rsa_common.txt, SymCryptProvider/src/asymcipher/p_scossl_rsa_cipher.c, SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c, SymCryptProvider/src/p_scossl_rsa.h, SymCryptProvider/src/signature/p_scossl_rsa_signature.c
Generated RSASSA-PSS format keys were not properly restricted to PSS padding. This PR properly restricts generated RSASSA-PSS keys to PSS padding and cleans up how those keys are indicated by key type.
=> Restrict padding for generated RSASSA-PSS keys

SymCryptProvider/src/p_scossl_base.c
TLS min/max version values were being passed to OpenSSL rather than DTLS min/max versions
=> fix cut-n-paste bug

ScosslCommon/src/scossl_dh.c, ScosslCommon/src/scossl_ecc.c, SymCryptProvider/src/kdf/p_scossl_sskdf.c, SymCryptProvider/src/kdf/p_scossl_tls1prf.c, SymCryptProvider/src/keymgmt/p_scossl_dh_keymgmt.c, SymCryptProvider/src/keymgmt/p_scossl_ecc_keymgmt.c, SymCryptProvider/src/p_scossl_base.c, SymCryptProvider/src/p_scossl_keysinuse.c, SymCryptProvider/src/p_scossl_rsa.c
This PR fixes a couple bugs related to keysinuse and memory leaks found with additional valgrind testing.
- Create `/var/log/keysinuse` with correct permissions and ownership if not found on keysinuse start.
- Fix double alloc in X25519 case. Fixes #108 
- Fix edge case potential deadlock with RSA keys
- Add static flag to initialize DH and ECC curves only once. If the engine and provider are both loaded these hidden curves were re-initialized and the originally created curves are leaked.
- Fix some additional leaks found with valgrind testing
=> KeysInUse and memory fixes

SymCryptProvider/src/p_scossl_base.c
`SCOSSL_MAX_CONFIGURABLE_FILE_SIZE` was originally intended to be the default max file size for KeysInUse in cases where the configured max file size overflowed an `off_t`. This behavior is inconsistent and confusing, since a user would be allowed to set the max file size to something like 100GB but would be capped at 2GB in case of a bad configuration leading to overflow. Either case is unlikely, and there isn't a real use case for letting this file grow past 2GB.
This PR enforces `SCOSSL_MAX_CONFIGURABLE_FILE_SIZE` as the max configurable file size as the name implies.
=> Clamp keysinuse max file size to SCOSSL_MAX_CONFIGURABLE_FILE_SIZE

ScosslCommon/inc/scossl_aes_aead.h, ScosslCommon/src/scossl_aes_aead.c, SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c
The SymCrypt unit tests with OpenSSL and SCOSSL revealed an edge case when calling `EVP_CipherInit_ex2` and passing the IV length as a parameter alongside the IV. The SCOSSL implementation unconditionally freed the set IV if an IV length was set, even if the IV length did not change. If the IV length matches what's set, then the IV should not be reset.
This PR also adds state checks for the IV and tag in CCM to bring the behavior and failure points more in line with the default provider.
=> Proper state management for AES GCM and CCM

CMakeLists.txt, SslPlay/CMakeLists.txt, SymCryptProvider/README.md, cmake-toolchain/LinuxUserMode-AMD64.cmake, cmake-toolchain/LinuxUserMode-ARM.cmake, cmake-toolchain/LinuxUserMode-ARM64.cmake
This is a small PR to disable optimizations for debug and sanitize builds, and fixes typos in the readme. This PR also removes '-dev' from the cmake lists since cmake only supports numeric version numbers.
=> Only compile with optimizations for release builds and fix typos

SslPlay/SslPlay.cpp, SymCryptEngine/src/e_scossl_rsa.c, SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c
support RSA key size 512 generate in SymCrypt provider.
Testing:
added: TestRsaEvp(512, 65537)
sslplay passed.
=> Support RSA512 generate in SymCrypt provider

ScosslCommon/src/scossl_dh.c, SslPlay/SslPlay.cpp, SymCryptEngine/README.md, SymCryptEngine/src/e_scossl_dh.c, SymCryptProvider/README.md, SymCryptProvider/src/keymgmt/p_scossl_dh_keymgmt.c, SymCryptProvider/src/p_scossl_base.c
Support ffdhe6144 and ffdhe8192 in the SymCrypt provider
testing:
added ffdhe6144 and ffdhe8192 in sslplay. sslplay passed.
=> FFDHE: Support ffdhe6144 and ffdhe8192 in the SymCrypt provider

SymCryptProvider/src/kdf/p_scossl_hkdf.c, test/KeysInUseTest/KeysInUseTest.cpp
- Expose `OSSL_KDF_PARAM_INFO` for HKDF and TLS13-KDF
- Only compile KeysInUse tests with `prime192v1` if it's available. The curve is not available on Azure Linux 3.
=> Bugfixes for tests

SymCryptProvider/src/ciphers/p_scossl_aes.c
CFB fix. change the blocksize to 1 for all CFBs per 
https://docs.openssl.org/3.0/man3/EVP_EncryptInit/#gettable-evp_cipher-parameters:~:text=%22blocksize%22%20(OSSL_CIPHER_PARAM_BLOCK_SIZE,the%20cached%20value.
test:
(1) test code from sql team passed.
(2) sslplay passed.
(3) buddy pipeline, functional test pipeline successfully.
=> CFB fix. change the blocksize to 1 for all CFBs

SymCryptProvider/src/ciphers/p_scossl_aes.c
Fix for TLS 1.x CBC ciphersuites (#130)
Builds on fix: compatibility issue between SCOSSL and TLS 1.2 ciphersuites which use HMAC in AzL3 #129 but handles overly large padding on decryption
Addresses bug 58142883
Error Message:
openssl s_client -connect tcs.microsoftstore.com.cn:443 -tls1_2 -cipher ECDHE-RSA-AES256-SHA384 40D79C8E857B0000:error:0A0003FC:SSL routines:ssl3_read_bytes:ssl/tls alert bad record mac:ssl/record/rec_layer_s3.c:907:SSL alert number 20
Root cause:
(1) TLS1.2 uses PKCS7-like padding for CBC cipher modes, but it is not PKCS7. SCOSSL was using PKCS7 padding incorrectly in TLS CBC paths, both causing errors on encryption path (other party would expect padding to be one byte longer and normally fail in padding check, if not in subsequent MAC check), and the decryption …
=> Cherrypick TLS 1.x CBC ciphersuites fix on SCOSSL 1.9

ScosslCommon/src/scossl_aes_aead.c, ScosslCommon/src/scossl_mac.c, ScosslCommon/src/scossl_tls1prf.c, SymCryptProvider/src/ciphers/p_scossl_aes_aead.c, SymCryptProvider/src/ciphers/p_scossl_aes_xts.c, SymCryptProvider/src/digests/p_scossl_cshake.c, SymCryptProvider/src/kdf/p_scossl_hkdf.c, SymCryptProvider/src/kdf/p_scossl_pbkdf2.c, SymCryptProvider/src/kdf/p_scossl_srtpkdf.c, SymCryptProvider/src/kdf/p_scossl_sshkdf.c, SymCryptProvider/src/kdf/p_scossl_tls1prf.c, SymCryptProvider/src/kem/p_scossl_mlkem.c, SymCryptProvider/src/keyexch/p_scossl_dh.c, SymCryptProvider/src/keyexch/p_scossl_ecdh.c, SymCryptProvider/src/keymgmt/p_scossl_dh_keymgmt.c, SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c, SymCryptProvider/src/mac/p_scossl_hmac.c, SymCryptProvider/src/p_scossl_ecc.c
+ In testing previous fix I hit an issue where an uninitialized value was freed with keysinused enabled when duplicating an ECC key context
+ I looked through all use of OPENSSL_malloc and ensured that values are initialized before use - in some places this is fixed most easily by using OPENSSL_zalloc, in others I refactored the code to be more explicit
+ In refactoring, also fixed some bugs here and there (i.e. hybrid ML-KEM dupctx never duplicated the classic keyexchange ctx, CShake dupctx would segfault on failed allocation rather than fail gracefully)
+ Also fix potential for memory leak in `scossl_aes_gcm_init_ctx` when an iv is passed and the ctx was previously initialized
+ This cannot affect the provider as only freshly allocated contexts are initialized, and then only with a NULL …
=> Fix use of uninitialized memory and consistency of code handling allocations

ScosslCommon/src/scossl_aes_aead.c, ScosslCommon/src/scossl_helpers.c, ScosslCommon/src/scossl_mac.c, ScosslCommon/src/scossl_tls1prf.c, SymCryptProvider/src/ciphers/p_scossl_aes_aead.c, SymCryptProvider/src/ciphers/p_scossl_aes_xts.c, SymCryptProvider/src/digests/p_scossl_cshake.c, SymCryptProvider/src/kdf/p_scossl_hkdf.c, SymCryptProvider/src/kdf/p_scossl_pbkdf2.c, SymCryptProvider/src/kdf/p_scossl_srtpkdf.c, SymCryptProvider/src/kdf/p_scossl_sshkdf.c, SymCryptProvider/src/kdf/p_scossl_tls1prf.c, SymCryptProvider/src/keyexch/p_scossl_dh.c, SymCryptProvider/src/keyexch/p_scossl_ecdh.c, SymCryptProvider/src/keymgmt/p_scossl_dh_keymgmt.c, SymCryptProvider/src/keymgmt/p_scossl_ecc_keymgmt.c, SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c, SymCryptProvider/src/mac/p_scossl_hmac.c, SymCryptProvider/src/p_scossl_keysinuse.c
This is mostly a cherry-pick of #133, but there has been some divergence between 1.9 and main, specifically around KeysInUse and ECC, so needed a little extra work.
- Found a couple of extra hardening measures to bring back to main in the second commit, notably:
- Remove paths for UB in failure to allocate `CRYPTO_THREAD_lock`
- Remove paths for use of uninitialized memory `p_scossl_rsa_keygen`
Tests:
- Ran SslPlay under valgrind on AzL3 with these changes and no regressions
=> Fix use of uninitialized memory and consistency of code handling allocations on SCOSSL 1.9

KeysInUse/keysinuse.c, ScosslCommon/src/scossl_helpers.c, SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c
* Based on additional fixes made when porting previous fix to 1.9 branch (#135)
* Check for failure in CRYPTO_THREAD_lock_new
* Reduce scope for unexpected behavior in RSA keygen
=> Additional allocation hardening

KeysInUse/keysinuse.c, ScosslCommon/src/scossl_aes_aead.c, ScosslCommon/src/scossl_helpers.c, ScosslCommon/src/scossl_mac.c, ScosslCommon/src/scossl_tls1prf.c, SymCryptProvider/src/ciphers/p_scossl_aes.c, SymCryptProvider/src/ciphers/p_scossl_aes_aead.c, SymCryptProvider/src/ciphers/p_scossl_aes_xts.c, SymCryptProvider/src/digests/p_scossl_cshake.c, SymCryptProvider/src/kdf/p_scossl_hkdf.c, SymCryptProvider/src/kdf/p_scossl_pbkdf2.c, SymCryptProvider/src/kdf/p_scossl_srtpkdf.c, SymCryptProvider/src/kdf/p_scossl_sshkdf.c, SymCryptProvider/src/kdf/p_scossl_tls1prf.c, SymCryptProvider/src/kem/p_scossl_mlkem.c, SymCryptProvider/src/keyexch/p_scossl_dh.c, SymCryptProvider/src/keyexch/p_scossl_ecdh.c, SymCryptProvider/src/keymgmt/p_scossl_dh_keymgmt.c, SymCryptProvider/src/keymgmt/p_scossl_ecc_keymgmt.c, SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c, SymCryptProvider/src/mac/p_scossl_hmac.c, SymCryptProvider/src/p_scossl_ecc.c
Fast-forward scossl-1.10 to include commits from main
=> Fast-forward scossl-1.10 to include commits from main

SymCryptProvider/src/p_scossl_keysinuse.c
KeysInUse has a double mutex unlock in `p_scossl_keysinuse_teardown`. This was fixed in main, and this PR brings this fix to 1.9.
=> Fix double unlock in keysinuse teardown

SymCryptProvider/src/p_scossl_keysinuse.c
This reverts commit 1c2f0f08998bfb0900ca724878d449febb8d23d8.
Testing with development binaries revealed a potential regression. Reverting this commit for further testing.
=> Revert "Support forking processes for KeysInUse (#146)"
